### ISSUE TITLE
overlays-management-hub module does not appear to support enable_management_logging parameter

### ISSUE THREAD

**Issue by timothymeyers** [azurenoops/ref-scca-enclave-starter#13]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

Run `terraform plan -var-file=parameters.tfvars`

### Any log messages given by the failure

<img width="436" alt="image" src="https://github.com/azurenoops/ref-scca-enclave-starter/assets/5417850/264366d8-7c35-4303-9c44-f627e0035c47">

Note that `enable_management_logging` is not listed [here ](https://registry.terraform.io/modules/azurenoops/overlays-management-hub/azurerm/2.0.7?tab=inputs) as a valid input.

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jrspinella** [comment]
This not a bug as we made an architecture decision not to make the logging optional. Since most of our modules are opinionated to the SCCA, logging is not optional. We updated the Management-Hub on version [v2.0.7](https://github.com/azurenoops/terraform-azurerm-overlays-management-hub/releases/tag/v2.0.7) to remove the option. We will need to update the docs to reflect this. https://github.com/azurenoops/ref-scca-enclave-starter/issues/18
